config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  # Authorization
  authenticated :user do 
    root "docs#index", as: "authenticated_root"
  end

  # landing page
  root 'welcome#index'

  resources :docs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController

    before_action :find_doc, only: [:show, :edit, :update, :destroy]

    def index
        @docs = Doc.where(user_id: current_user).order("created_at DESC")
    end

    def show
    end

    def new
        @doc = current_user.docs.build
    end

    def create
        @doc = current_user.docs.build(doc_params)

        if @doc.save
            redirect_to @doc
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @doc.update(doc_params)
            redirect_to @doc
        else
            render 'edit'
        end
    end

    def destroy
        @doc.destroy
        redirect_to @doc
    end

    private
        def find_doc
            @doc = Doc.find(params[:id])
        end

        def doc_params
            params.require(:doc).permit(:title, :content)
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    =f.input :title
    =f.input :content
    =f.button :submit
    

app/views/docs/edit.html.haml
%h1 Fix Doc

= render 'form'

= link_to "Cancel", doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
    #docs.clearfix
        -unless @docs.blank?
            - @docs.each do |doc|
                .doc
                    %h1.title= link_to doc.title, doc
                    %p.date= time_ago_in_words(doc.created_at)
                    %p.content= truncate(doc.content, length:50)
        -else
            %h2 Create A doc
            button= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
%h1 new

= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content

= link_to "All Docs", docs_path
= link_to "Fix Doc", edit_doc_path(@doc) 
= link_to "Trash It", doc_path(@doc), method: :delete, data: {confirm: "Are You Sure"}

app/views/layouts/application.html.haml
%html
%head
  %title Filecabnet | Private Docs
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
  = csrf_meta_tags
%body
  %header 
    .header_inner
      = link_to "FileCabnet", root_path, id: "logo"

      %nav
        -if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        -else
          = link_to "Log In", new_user_session_path
  %p.notice
  %p.alert

  = yield

app/views/welcome/index.html.haml
#banner
    .banner_content
        %h1 File Cabnet
        %p Your Personal Private File Cabnet
        %button= link_to "Enter", new_user_registration_path
#callouts
    .callout_inner
        .wrapper   
            .callout
                %h2 Organize
                %p Kitsch tofu leggings pork belly authentic hell of pok pok put a bird on it mlkshk bushwick. Gastropub hoodie iceland health goth ugh. PBR&B +1 cred chia brunch. Freegan kale chips craft beer stumptown bespoke.
    
#bottom_cta
    .wrapper
        %h2 Go Ahead!
        %br
        %button= link_to "Join Now", new_user_registration_path